---
title: "R Notebook"
output: html_notebook
---
```{r}
df=read.csv("F:\\R Scripts\\Data\\WA_Fn-UseC_-HR-Employee-Attrition.csv")
df
```
```{r}
df$Attrition[df$Attrition=="Yes"]=1
df$Attrition[df$Attrition=="No"]=0
df$Attrition=as.numeric(df$Attrition)
```
```{r}
df[,c(2,4,6,7,11,15,17,22)]=lapply(df[,c(2,4,6,7,11,15,17,22)],as.factor)
```
```{r}
df$Over18[df$Over18=="Y"]=1
df$Over18=as.numeric(df$Over18)
df$Over18
```
```{r}
summary(df)
```


```{r}
set.seed(1000)
ranuni=sample(x=c("Training","Testing"),size=nrow(df),replace=T,prob=c(0.7,0.3))
TrainingData=df[ranuni=="Training",]
TestingData=df[ranuni=="Testing",]
nrow(TrainingData)
nrow(TestingData)
```
```{r}
independentvariables=colnames(df[,2:35])
independentvariables
Model=paste(independentvariables,collapse="+")
Model
Model_1=paste("Attrition~",Model)
Model_1
class(Model_1)
formula=as.formula(Model_1)
formula
```
```{r}
Trainingmodel1=glm(formula=formula,data=TrainingData,family="binomial")
```
```{r}
Trainingmodel1=step(object = Trainingmodel1,direction = "both")
summary(Trainingmodel1)
```
```{r}
HLgof.test(fit=Trainingmodel1$fitted.values,obs=Trainingmodel1$y)
```
```{r}

```



